/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include "actual360.hpp"
#include "actual364.hpp"
#include "actual365fixed.hpp"
#include "actualactual.hpp"
#include "business252.hpp"
#include "one.hpp"
#include "simpledaycounter.hpp"
#include "thirty360.hpp"
#include "thirty365.hpp"

